<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BukuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('bukus')->insert([
            [
                'kategori_id' => 1,
                'judul' => 'Atomic Habits',
                'penulis' => 'James Clear',
                'penerbit' => 'Penguin Random House',
                'isbn' => '9780735211292',
                'tahun' => '2018',
                'jumlah' => 5,
                'deskripsi' => 'Atomic Habits menjelaskan bagaimana perubahan kecil dan konsisten dapat menghasilkan hasil yang luar biasa. James Clear memberikan strategi praktis untuk membangun kebiasaan baik dan menghilangkan kebiasaan buruk.',
            ],
            [
                'kategori_id' => 2,
                'judul' => 'The Power of Habit',
                'penulis' => 'Charles Duhigg',
                'penerbit' => 'Random House',
                'isbn' => '9780812981605',
                'tahun' => '2012',
                'jumlah' => 7,
                'deskripsi' => 'Buku ini mengungkapkan bagaimana kebiasaan terbentuk, bagaimana mereka bekerja, dan bagaimana kita dapat mengubahnya. Duhigg menggunakan penelitian ilmiah dan kisah nyata untuk menjelaskan kekuatan kebiasaan dalam kehidupan sehari-hari.',
            ],
            [
                'kategori_id' => 3,
                'judul' => 'Thinking, Fast and Slow',
                'penulis' => 'Daniel Kahneman',
                'penerbit' => 'Farrar, Straus and Giroux',
                'isbn' => '9780374275631',
                'tahun' => '2011',
                'jumlah' => 3,
                'deskripsi' => 'Daniel Kahneman, pemenang Nobel, menjelaskan dua sistem berpikir yang mempengaruhi keputusan kita: sistem cepat dan intuitif, serta sistem lambat dan analitis. Buku ini mengajak pembaca untuk memahami bias dan kesalahan dalam berpikir.',
            ],
            [
                'kategori_id' => 4,
                'judul' => 'Sapiens: A Brief History of Humankind',
                'penulis' => 'Yuval Noah Harari',
                'penerbit' => 'Harper',
                'isbn' => '9780062316097',
                'tahun' => '2011',
                'jumlah' => 8,
                'deskripsi' => 'Harari membawa pembaca dalam perjalanan melalui sejarah manusia, dari evolusi Homo sapiens hingga perkembangan masyarakat modern. Buku ini mengeksplorasi bagaimana budaya, agama, dan ekonomi membentuk dunia kita.',
            ],
            [
                'kategori_id' => 5,
                'judul' => 'The Psychology of Money',
                'penulis' => 'Morgan Housel',
                'penerbit' => 'Harriman House',
                'isbn' => '9780857197689',
                'tahun' => '2020',
                'jumlah' => 6,
                'deskripsi' => 'Morgan Housel membahas bagaimana perilaku dan psikologi mempengaruhi keputusan keuangan kita. Buku ini menekankan pentingnya memahami hubungan kita dengan uang dan bagaimana hal itu dapat memengaruhi kebahagiaan kita.',
            ],
            [
                'kategori_id' => 6,
                'judul' => 'Deep Work',
                'penulis' => 'Cal Newport',
                'penerbit' => 'Grand Central Publishing',
                'isbn' => '9781455586691',
                'tahun' => '2016',
                'jumlah' => 4,
                'deskripsi' => 'Cal Newport menjelaskan pentingnya fokus mendalam dalam dunia yang penuh gangguan. Buku ini memberikan strategi untuk meningkatkan produktivitas dan mencapai hasil yang lebih baik dalam pekerjaan.',
            ],
            [
                'kategori_id' => 7,
                'judul' => 'Ikigai: The Japanese Secret to a Long and Happy Life',
                'penulis' => 'Héctor García, Francesc Miralles',
                'penerbit' => 'Penguin Books',
                'isbn' => '9780143130727',
                'tahun' => '2017',
                'jumlah' => 10,
                'deskripsi' => 'Buku ini mengeksplorasi konsep ikigai, yang berarti "alasan untuk bangun di pagi hari". Penulis membahas bagaimana menemukan tujuan hidup dapat meningkatkan kebahagiaan dan umur panjang.',
            ],
            [
                'kategori_id' => 8,
                'judul' => 'The Subtle Art of Not Giving a F*ck',
                'penulis' => 'Mark Manson',
                'penerbit' => 'HarperOne',
                'isbn' => '9780062457714',
                'tahun' => '2016',
                'jumlah' => 9,
                'deskripsi' => 'Mark Manson menantang pandangan positif yang berlebihan dan mengajak pembaca untuk fokus pada hal-hal yang benar-benar penting dalam hidup. Buku ini memberikan perspektif baru tentang kebahagiaan dan makna.',
            ],
            [
                'kategori_id' => 9,
                'judul' => 'Rich Dad Poor Dad',
                'penulis' => 'Robert Kiyosaki',
                'penerbit' => 'Plata Publishing',
                'isbn' => '9781612680194',
                'tahun' => '1997',
                'jumlah' => 2,
                'deskripsi' => 'Kiyosaki membandingkan dua pola pikir tentang uang melalui kisah hidupnya. Buku ini mengajarkan pentingnya pendidikan finansial dan investasi untuk mencapai kebebasan finansial.',
            ],
            [
                'kategori_id' => 10,
                'judul' => 'The 7 Habits of Highly Effective People',
                'penulis' => 'Stephen R. Covey',
                'penerbit' => 'Free Press',
                'isbn' => '9780743269513',
                'tahun' => '1989',
                'jumlah' => 7,
                'deskripsi' => 'Covey memperkenalkan tujuh kebiasaan yang dapat membantu individu menjadi lebih efektif dalam kehidupan pribadi dan profesional. Buku ini menekankan pentingnya prinsip dan nilai dalam mencapai tujuan.',
            ],
            [
                'kategori_id' => 11,
                'judul' => 'Start with Why',
                'penulis' => 'Simon Sinek',
                'penerbit' => 'Penguin',
                'isbn' => '9781591846444',
                'tahun' => '2009',
                'jumlah' => 5,
                'deskripsi' => 'Sinek menjelaskan pentingnya memiliki "mengapa" yang jelas dalam bisnis dan kehidupan. Buku ini menunjukkan bagaimana pemimpin yang sukses menginspirasi orang lain dengan visi yang kuat.',
            ],
            [
                'kategori_id' => 12,
                'judul' => 'The Lean Startup',
                'penulis' => 'Eric Ries',
                'penerbit' => 'Crown Business',
                'isbn' => '9780307887894',
                'tahun' => '2011',
                'jumlah' => 6,
                'deskripsi' => 'Ries memperkenalkan metode Lean Startup untuk membantu pengusaha membangun bisnis yang lebih efisien dan inovatif. Buku ini menekankan pentingnya eksperimen dan umpan balik dalam pengembangan produk.',
            ],
            [
                'kategori_id' => 13,
                'judul' => 'Zero to One',
                'penulis' => 'Peter Thiel',
                'penerbit' => 'Crown Business',
                'isbn' => '9780804139298',
                'tahun' => '2014',
                'jumlah' => 8,
                'deskripsi' => 'Thiel membahas bagaimana menciptakan sesuatu yang baru dan unik, serta pentingnya inovasi dalam bisnis. Buku ini memberikan wawasan tentang cara berpikir yang berbeda untuk mencapai kesuksesan.',
            ],
            [
                'kategori_id' => 14,
                'judul' => 'The Art of War',
                'penulis' => 'Sun Tzu',
                'penerbit' => 'Shambhala',
                'isbn' => '9781590302255',
                'tahun' => '5th Century BC',
                'jumlah' => 3,
                'deskripsi' => 'Karya klasik ini membahas strategi dan taktik dalam perang, tetapi juga dapat diterapkan dalam kehidupan sehari-hari dan bisnis. Sun Tzu mengajarkan pentingnya perencanaan dan adaptasi.',
            ],
            [
                'kategori_id' => 15,
                'judul' => 'The Alchemist',
                'penulis' => 'Paulo Coelho',
                'penerbit' => 'HarperOne',
                'isbn' => '9780062315007',
                'tahun' => '1988',
                'jumlah' => 9,
                'deskripsi' => 'Novel ini mengikuti perjalanan Santiago, seorang gembala muda yang mencari harta karun. Buku ini mengajarkan tentang pentingnya mengikuti impian dan menemukan makna hidup.',
            ],
            [
                'kategori_id' => 16,
                'judul' => 'Educated: A Memoir',
                'penulis' => 'Tara Westover',
                'penerbit' => 'Random House',
                'isbn' => '9780399590504',
                'tahun' => '2018',
                'jumlah' => 4,
                'deskripsi' => 'Memoir ini menceritakan perjalanan Tara dari kehidupan yang terisolasi di Idaho hingga mendapatkan gelar PhD dari Cambridge. Buku ini menggambarkan kekuatan pendidikan dan pencarian identitas.',
            ],
            [
                'kategori_id' => 17,
                'judul' => 'Can\'t Hurt Me',
                'penulis' => 'David Goggins',
                'penerbit' => 'Lioncrest Publishing',
                'isbn' => '9781544512273',
                'tahun' => '2018',
                'jumlah' => 7,
                'deskripsi' => 'Goggins menceritakan kisah hidupnya yang penuh tantangan dan bagaimana ia mengatasi rintangan untuk mencapai kesuksesan. Buku ini menginspirasi pembaca untuk mengembangkan ketahanan mental.',
            ],
            [
                'kategori_id' => 18,
                'judul' => 'How to Win Friends and Influence People',
                'penulis' => 'Dale Carnegie',
                'penerbit' => 'Simon & Schuster',
                'isbn' => '9780671027032',
                'tahun' => '1936',
                'jumlah' => 6,
                'deskripsi' => 'Buku klasik ini memberikan prinsip-prinsip untuk membangun hubungan yang baik dan mempengaruhi orang lain. Carnegie menawarkan teknik yang dapat diterapkan dalam kehidupan sehari-hari.',
            ],
            [
                'kategori_id' => 19,
                'judul' => 'Good to Great',
                'penulis' => 'Jim Collins',
                'penerbit' => 'HarperBusiness',
                'isbn' => '9780066620991',
                'tahun' => '2001',
                'jumlah' => 5,
                'deskripsi' => 'Collins menganalisis perusahaan-perusahaan yang berhasil bertransformasi dari baik menjadi hebat. Buku ini mengidentifikasi faktor-faktor kunci yang berkontribusi pada kesuksesan jangka panjang.',
            ],
            [
                'kategori_id' => 20,
                'judul' => 'Man\'s Search for Meaning',
                'penulis' => 'Viktor E. Frankl',
                'penerbit' => 'Beacon Press',
                'isbn' => '9780807014295',
                'tahun' => '1946',
                'jumlah' => 3,
                'deskripsi' => 'Frankl, seorang psikiater dan penyintas Holocaust, membahas pencarian makna hidup di tengah penderitaan. Buku ini mengajarkan bahwa makna dapat ditemukan bahkan dalam situasi yang paling sulit.',
            ]
        ]);
    }
}